.env-example, .github/PULL_REQUEST_TEMPLATE.md, .vscode/launch.json, src/bot.js, src/chat.js, src/config.js, src/discord.js, src/server.js
- Modularize the client so that it's easier to run with minimum configuration needed.
- Get the code
```
cd ttv-chat-light
git checkout environment-module
npm install
```
- You can run the client with just the overlay component and not the discord or bot components
=> Environment module

src/bot.js, src/chat.js, src/server.js
- ...
- Get the code
```
cd ttv-chat-light
npm install
```
- ...
=> Fix colors and effects being applied to the overlay

.vscode/launch.json, README.md, package-lock.json, src/client/stream.ts, src/server/azure-bot.ts, src/server/twitch-chat.ts
- Fixes issues where the "cop mode" effect wasn't working properly
- it was running twice
- it was using the incorrect colors
- Add new launch configurations so we can debug the client and the server via a compound launch config
- Get the code
```
git checkout fix-effect-ts
npm install
```
- cop mode effect changes the overlay colors properly
=> fix special effects triggering twice & correct colors. add new launches

src/server/alerts-manager.ts, src/server/azure-bot.ts, src/server/effects-manager.ts, src/server/effects.json, src/server/overlay.ts, src/server/twitch-chat.ts
- Addresses #43 to better handle and drive effects dynamically
=> Better effects handling

README.md
Update readme for #hactoberfest assuming PR #46 is accepted.
- ...
- [X ] No
- [X ] Documentation content changes
- Get the code
```
npm install
```
Verify that the readme includes eeevans
- ...Code will build
=> Update readme to include myself as contributor.

TODO, package-lock.json, package.json, src/server/effects-manager.ts, src/server/effects.json, src/server/file-manager.ts, src/server/obs-manager.ts, src/server/overlay.ts, src/server/sound-fx.ts
- Add capabilites to trigger scene effects driven by effect definitions in an effects.json file
- Leverages the websockets server plugin for OBS
=> OBS Scene Effects

TODO, package-lock.json, src/server/effects-manager.ts, src/server/effects.json, src/server/obs-manager.ts, src/server/twitch-chat.ts
- Adds capabilities to control the active scene used in OBS and therefore shown on screen.
=> Add Scene Command

src/server/effects.json
Adding the iliketurtles sound for when ToeFrog joins the stream
Play the "iliketurtles" sound byte when ToeFrog joins the stream.
- ...
- [X ] No
- [X ] Feature
See if soundbyte plays when ToeFrog joins the stream. :)
- Get the code
```
npm install
```
- ...
=> adding toefrog join sound

src/server/effects-manager.ts
- ...
- Get the code
```
npm install
```
- ...
=> fix user join sounds to play once per session

CONTRIBUTING.md, README.md, package-lock.json, package.json, src/server/alerts-manager.ts, src/server/azure-bot.ts, src/server/config.ts, src/server/discord-bot.ts, src/server/routes/save-css.ts, src/server/sound-fx.ts, src/server/tsconfig.json, src/server/twitch-chat.ts, tslint.json
Tidy up the code base
I recommend walking through each commit to get a better feel of the iterative changes I have made. I opted to make it one PR to avoid spamming
=> Housekeeping

src/server/effects.json
- Adds a join sound for goonpontoon
- Get the code
```
npm install
```
- ...
=> Added join sound for myself

src/server/effects.json
- ...
- Get the code
```
npm install
```
- ...
=> add moar effects

src/server/effects-manager.ts, src/server/effects.json
- ...
- Get the code
```
npm install
```
- ...
=> play 'sorry' when a user passed an invalid command

TODO, src/server/alerts-manager.ts, src/server/azure-bot.ts, src/server/constants.ts, src/server/effects-manager.ts, src/server/index.ts, src/server/obs-manager.ts, src/server/overlay.ts, src/server/server.ts, src/server/sound-fx.ts, src/server/twitch-chat.ts
- ...
- Get the code
```
npm install
```
- ...
=> Refactor remove magic strings

TODO, src/assets/styles.css, src/client/stream.ts
- ...
- Get the code
```
npm install
```
- ...
=> Fix overlay color change

src/client/stream.ts
Replace standard audio with the HTML5 Audio object
- [X ] No
- [X ] Bugfix
Try running fart
```
=> Give this audio a go, slightly rejigged

src/server/twitch-chat.ts, src/server/twitch-user.ts
- ...
- Get the code
```
npm install
```
- ...
=> capture user details on chat message

.vscode/launch.json, TODO, package-lock.json, package.json, src/client/stream.ts, src/client/tsconfig.json, src/server/constants.ts, src/server/effects-manager.ts, src/server/file-manager.ts, src/server/sound-fx.ts, views/index.pug
- ...
- Get the code
```
npm install
```
- ...
=> Soundfx via browser

src/client/text-to-speech.ts, src/server/effects-manager.ts, src/server/twitch-chat.ts, src/server/twitch-user.ts, views/index.pug
- ...
- Get the code
```
npm install
```
- ...
=> Working Solution and is better thanks to Twitch chat friends!!!!

.vscode/launch.json, .vscode/tasks.json, package-lock.json, package.json, src/client/text-to-speech.ts, src/client/tsconfig.json, src/server/config.ts, src/server/routes/tokens.ts, src/server/server.ts, tts.todo, views/index.pug
- Removes use of browser based speech synthesis and switches to Azure Text-to-Speech service
- Get the code
```
npm install
```
- ...
=> Text-to-Speech with Azure

src/server/obs-handler.ts
- ...
- Get the code
```
npm install
```
- ...
=> fix: obs websocket connection retry logic

package-lock.json, package.json
- ...
- Get the code
```
npm install
```
- ...
=> fix audit notices

package-lock.json, package.json
- ...
- Get the code
```
npm install
```
- ...
=> fix: address moar dependency audit stuffs

src/server/effects-service.ts, src/server/obs-handler.ts, src/server/tau-alerts.ts, src/server/tau-api.ts, src/server/twitch-chat.ts
fix: remove unneccessary logs
- ...
- Get the code
```
npm install
```
- ...
=> feat: autocomplete shadow redemption
